pipeline:
  docker-latest:
    image: plugins/docker
    repo: registry.usw.co/uswitch/etcd-srv-bootstrap
    tag:
      - latest
    dockerfile: Dockerfile
    when:
      event: push
      branch: master

  docker-versioned:
    image: plugins/docker
    repo: registry.usw.co/uswitch/etcd-srv-bootstrap
    tag:
     - ${DRONE_TAG}
    dockerfile: Dockerfile
    when:
      event: tag
